version: '3'

services:
  db:
    image: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin12345
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./.postgres-data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
       - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db